### ISSUE TITLE
keras_ocr -> onnx -> trt

### ISSUE THREAD

**Issue by jusonn** [mukaman84/ocrSecurity#2]

**Comment by jusonn** [comment]
@mukaman84 여기 확인점
https://github.com/jusonn/ocrSecurity/commit/f4d9034ca00445526b6f0cbeeb7863563cd3ec84#r37522329

**Comment by jusonn** [comment]
여기서 에러 발생
```
transformed_image = tf.add_n([
        area_a * pixel_values_a, area_b * pixel_values_b, area_c * pixel_values_c,
        area_d * pixel_values_d
    ])
```

**Comment by jusonn** [comment]
add_n 관련 코드 https://github.com/jusonn/ocrSecurity/commit/231c4ad1d46bdfc18417bd7240dd68978f683625#r37554438

**Comment by mukaman84** [comment]
this issue is resolved. if need, reopen please.
